### ISSUE TITLE
Create standalone node module + drop in GAE server

### ISSUE THREAD

**Issue by ghost** [GoogleChrome/http2push-gae#5]
It would be awesome if this was integrated as an option into the Polymer Starter Toolkit.

Not everyone can use a HTTP2  Server, so it should be an option as part of the gulp script and app.js ?

**Comment by ebidel** [comment]
There's already a [gulp script that generates the "manifest"](https://github.com/GoogleChrome/http2push-gae/blob/master/scripts/generate_push_manifest.js) of resources to push. You could use that and then construct the correct header: https://github.com/GoogleChrome/http2push-gae/blob/master/main.py#L91

Unfortunately, I see two problems with baking this into a starter kit.
1. The `X-Associated-Content` is deprecated. App Engine needs to support the standard `Link rel="preload"`. No idea on timeline for that.
2. This setup is very specific to GAE atm. That's not a blocker because with 1 fixed, you could use this as a progressively enhanced feature on any server that supports push.

I think what we should do short-term is:
1. Support the new header format, while continuing to make this one work with GAE
2. Do more testing around the optimal number of resources to push. At some point, it's probably too many to be useful.
3. Release a standalone script on npm that has the gulp support.

@igrigorik is anyone doing something like this already? If not, I'd be happy to. Sounds fun!

**Comment by addyosmani** [comment]
Started writing a comment, but @ebidel captured the sentiment well. This seems better placed as a standalone module/script than baked into starter kit :+1:

**Comment by ghost** [comment]
I can  adapt it for golang and goapp (that being Go AppEngine).

Without AppEngine, Caddy (https://github.com/mholt/caddy) is what i would use.
Within AppEngine, I am not sure where its at. I doubt AppEngine supports HTTP2 yet, but if anyone knows would be helpful.

**Comment by ebidel** [comment]
The title of this repo is "HTTP 2.0 push on App Engine" :)

**Comment by ebidel** [comment]
Update:
1. I have a standalone npm script that generates a manifest of an app's resources (css/html/js)
2. In addition, I have a decorator-based drop-in lib for App Engine that you can annotate a handler with. This enables the handler to do h2 push, reads the manifest file, and sets the appropriate headers.

**Comment by ghost** [comment]
@ebidel 

thanks. i had a look and makes sense.
i am currently working off the PSK as a base for a project, and am having a hard enough time with learning the new styling encapsulation.
also hydrolysis is not in in the current PSK script, and so i dnt want to break everything by bringing it into the PSK.

So, could i suggest that this be integrated into the PSK please, so me and others can move fast on using http2 push ?

**Comment by ebidel** [comment]
Released https://www.npmjs.com/package/http2-push-manifest to generate the manifest

This repo has also been updated to be a standalone drop-in decorator lib. See the examples here: 
https://github.com/GoogleChrome/http2push-gae#using-the-http2push-server-module
